#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# EJecutar polybar al iniciar el sistema
~/.config/polybar/./launch.sh

# Fondo de pantalla
feh --bg-fill /home/s1or/Pictures/fondo.jpg

# Bordeado de ventanas y transparencia
picom --experimental-backends &
bspc config border_width 0

# Seleccion de ventana con mouse
#bspc config focus_follows_pointer true

# Correccion del problema del cursor
xsetroot -cursor_name left_ptr &

# Prueba bat
sudo dpkg -i /home/s1or/Downloads/firefox/
